language: cpp

compiler:
  - gcc
  
install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:chris-lea/protobuf
  - sudo apt-get update
  - sudo apt-get install -y libexpat1-dev libbz2-dev openssl g++-4.9 libxml2 libxml2-dev uuid-dev protobuf-compiler libprotobuf-dev libgsasl7-dev libkrb5-dev libboost1.54-all-dev

script: 
  - pwd && env && echo $PATH
  - export CXX=g++-4.9 && export CC=gcc-4.9 && mvn clean test -Dtest=native_tests -Pnative -Drequire.libhdfs3=true  
  - cat hadoop-hdfs-project/hadoop-hdfs/target/native/contrib/libhdfs3/test/function/functiontest.xml
